export const THEME_STORAGE_KEY = "theme-preference";
export const THEME_CHANGE_EVENT = "portfolio-theme-change";
export const BRIGHT_SHUFFLE_STEPS = 5;
export const BRIGHT_SHUFFLE_STEP_MS = 64;

export type ThemeMode = "dark" | "bright";

export function normalizeThemePreference(value: string | null): ThemeMode | null {
  return value === "dark" || value === "bright" ? value : null;
}

export function resolveTheme(preference: ThemeMode | null): ThemeMode {
  return preference ?? "dark";
}

type BrightValues = Record<string, string>;

type BrightPalette = {
  name: string;
  values: BrightValues;
};

const overscrollBackdrops = [
  "#1746ff",
  "#00f0b5",
  "#f5ff3d",
  "#ff4fd8",
  "#ff5a00",
  "#8b1dff",
  "#6dff94",
  "#00d1ff",
  "#f3ff2f",
  "#cc00ff",
] as const;

const retroCursors = [
  'url("/cursors/retro-pointer-cream.svg") 5 3, auto',
  'url("/cursors/retro-pointer-cobalt.svg") 5 3, auto',
  'url("/cursors/retro-pointer-acid.svg") 5 3, auto',
  'url("/cursors/retro-pointer-pink.svg") 5 3, auto',
  'url("/cursors/retro-pointer-orange.svg") 5 3, auto',
] as const;

const introCompanyHoverVariables = [
  "--intro-company-hover-opendoor",
  "--intro-company-hover-draftkings",
  "--intro-company-hover-coinbase",
  "--intro-company-hover-dropbox",
] as const;

const brightThemeVariables = [
  "--background",
  "--foreground",
  "--paper",
  "--paper-strong",
  "--surface",
  "--surface-strong",
  "--border",
  "--rule",
  "--muted",
  "--link-hover",
  "--accent",
  "--accent-soft",
  "--overscroll-background",
  "--shadow",
  "--shadow-soft",
  "--surface-panel-background",
  "--surface-card-background",
  "--header-surface",
  "--header-border",
  "--footer-border",
  "--intro-surface",
  "--intro-heading",
  "--gallery-divider",
  "--archive-note-surface",
  "--archive-note-border",
  "--archive-note-foreground",
  "--archive-note-muted",
  "--archive-preview-gradient",
  "--archive-placeholder-gradient",
  "--frame-surface-gradient",
  "--frame-spinner-surface",
  "--app-background-gradient",
  "--site-noise-overlay",
  "--site-noise-opacity",
  "--theme-toggle-surface",
  "--theme-toggle-border",
  "--theme-toggle-foreground",
  "--theme-toggle-hover-surface",
  "--theme-toggle-active-surface",
  "--theme-toggle-active-foreground",
  "--theme-toggle-shadow",
  "--zine-display-font",
  "--zine-body-font",
  "--zine-label-font",
  "--zine-heading-letter-spacing",
  "--zine-heading-text-transform",
  "--zine-body-letter-spacing",
  "--zine-label-letter-spacing",
  "--zine-label-text-transform",
  "--bright-opendoor-surface",
  "--bright-opendoor-heading",
  "--bright-opendoor-copy",
  "--bright-opendoor-meta",
  "--bright-opendoor-display-font",
  "--bright-opendoor-body-font",
  "--bright-opendoor-label-font",
  "--bright-opendoor-heading-letter-spacing",
  "--bright-opendoor-heading-text-transform",
  "--bright-opendoor-label-letter-spacing",
  "--bright-draftkings-surface",
  "--bright-draftkings-heading",
  "--bright-draftkings-copy",
  "--bright-draftkings-meta",
  "--bright-draftkings-display-font",
  "--bright-draftkings-body-font",
  "--bright-draftkings-label-font",
  "--bright-draftkings-heading-letter-spacing",
  "--bright-draftkings-heading-text-transform",
  "--bright-draftkings-label-letter-spacing",
  "--bright-coinbase-surface",
  "--bright-coinbase-heading",
  "--bright-coinbase-copy",
  "--bright-coinbase-meta",
  "--bright-coinbase-display-font",
  "--bright-coinbase-body-font",
  "--bright-coinbase-label-font",
  "--bright-coinbase-heading-letter-spacing",
  "--bright-coinbase-heading-text-transform",
  "--bright-coinbase-label-letter-spacing",
  "--bright-dropbox-surface",
  "--bright-dropbox-heading",
  "--bright-dropbox-copy",
  "--bright-dropbox-meta",
  "--bright-dropbox-display-font",
  "--bright-dropbox-body-font",
  "--bright-dropbox-label-font",
  "--bright-dropbox-heading-letter-spacing",
  "--bright-dropbox-heading-text-transform",
  "--bright-dropbox-label-letter-spacing",
];

function archiveFrameTokens({
  border,
  foreground,
  muted,
  spinner,
}: {
  border: string;
  foreground: string;
  muted: string;
  spinner: string;
}): BrightValues {
  return {
    "--archive-note-border": border,
    "--archive-note-foreground": foreground,
    "--archive-note-muted": muted,
    "--archive-preview-gradient": "var(--surface-card-background)",
    "--archive-placeholder-gradient": "var(--surface-strong)",
    "--frame-surface-gradient": "var(--surface-card-background)",
    "--frame-spinner-surface": spinner,
  };
}

const dropboxTypographyPresets = {
  serifCondensed: {
    "--bright-dropbox-display-font": "var(--font-zine-serif)",
    "--bright-dropbox-body-font": "var(--font-zine-readable)",
    "--bright-dropbox-label-font": "var(--font-zine-condensed)",
    "--bright-dropbox-heading-letter-spacing": "-0.045em",
    "--bright-dropbox-heading-text-transform": "none",
    "--bright-dropbox-label-letter-spacing": "0.16em",
  },
  elegantCompressed: {
    "--bright-dropbox-display-font": "var(--font-zine-elegant)",
    "--bright-dropbox-body-font": "var(--font-zine-readable)",
    "--bright-dropbox-label-font": "var(--font-zine-compressed)",
    "--bright-dropbox-heading-letter-spacing": "-0.035em",
    "--bright-dropbox-heading-text-transform": "none",
    "--bright-dropbox-label-letter-spacing": "0.1em",
  },
  literaryCompressed: {
    "--bright-dropbox-display-font": "var(--font-zine-literary)",
    "--bright-dropbox-body-font": "var(--font-zine-readable)",
    "--bright-dropbox-label-font": "var(--font-zine-compressed)",
    "--bright-dropbox-heading-letter-spacing": "-0.04em",
    "--bright-dropbox-heading-text-transform": "none",
    "--bright-dropbox-label-letter-spacing": "0.1em",
  },
  inkTypewriter: {
    "--bright-dropbox-display-font": "var(--font-zine-ink)",
    "--bright-dropbox-body-font": "var(--font-zine-readable)",
    "--bright-dropbox-label-font": "var(--font-zine-typewriter)",
    "--bright-dropbox-heading-letter-spacing": "-0.05em",
    "--bright-dropbox-heading-text-transform": "none",
    "--bright-dropbox-label-letter-spacing": "0.08em",
  },
} satisfies Record<string, BrightValues>;

const brightPalettes: BrightPalette[] = [
  {
    name: "citrus signal",
    values: {
      "--background": "#f5ff3d",
      "--foreground": "#11120a",
      "--paper": "#fff7c8",
      "--paper-strong": "#fffdf0",
      "--surface": "#fb8dff",
      "--surface-strong": "#fff3a6",
      "--border": "rgba(17, 18, 10, 0.24)",
      "--rule": "rgba(17, 18, 10, 0.18)",
      "--muted": "#504b21",
      "--link-hover": "#11120a",
      "--accent": "#004cff",
      "--accent-soft": "rgba(0, 76, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(68, 50, 0, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(68, 50, 0, 0.12)",
      "--surface-panel-background": "rgba(255, 253, 240, 0.88)",
      "--surface-card-background": "#fffdf0",
      "--header-surface": "rgba(245, 255, 61, 0.84)",
      "--header-border": "rgba(17, 18, 10, 0.18)",
      "--footer-border": "rgba(17, 18, 10, 0.18)",
      "--intro-surface": "#fb8dff",
      "--intro-heading": "#11120a",
      "--gallery-divider": "rgba(17, 18, 10, 0.14)",
      "--archive-note-surface": "#11120a",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.22)",
        foreground: "rgba(255, 253, 240, 0.9)",
        muted: "rgba(255, 253, 240, 0.68)",
        spinner: "rgba(255, 253, 240, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 253, 240, 0.82)",
      "--theme-toggle-border": "rgba(17, 18, 10, 0.2)",
      "--theme-toggle-foreground": "rgba(17, 18, 10, 0.64)",
      "--theme-toggle-hover-surface": "rgba(0, 76, 255, 0.12)",
      "--theme-toggle-active-surface": "#004cff",
      "--theme-toggle-active-foreground": "#fffdf0",
      "--theme-toggle-shadow": "0 18px 44px rgba(0, 76, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-poster)",
      "--zine-body-font": "var(--font-zine-grotesque)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "0",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.12em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffdf0",
      "--bright-opendoor-heading": "#11120a",
      "--bright-opendoor-copy": "#3f3515",
      "--bright-opendoor-meta": "#6b5a19",
      "--bright-opendoor-display-font": "var(--font-zine-serif)",
      "--bright-opendoor-body-font": "var(--font-zine-grotesque)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.025em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#11120a",
      "--bright-draftkings-heading": "#f5ff3d",
      "--bright-draftkings-copy": "rgba(255, 253, 240, 0.86)",
      "--bright-draftkings-meta": "#00f0b5",
      "--bright-draftkings-display-font": "var(--font-zine-poster)",
      "--bright-draftkings-body-font": "var(--font-zine-grotesque)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.08em",
      "--bright-coinbase-surface": "#004cff",
      "--bright-coinbase-heading": "#fffdf0",
      "--bright-coinbase-copy": "rgba(255, 253, 240, 0.86)",
      "--bright-coinbase-meta": "#f5ff3d",
      "--bright-coinbase-display-font": "var(--font-zine-grotesque)",
      "--bright-coinbase-body-font": "var(--font-zine-grotesque)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "-0.03em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#00f0b5",
      "--bright-dropbox-heading": "#11120a",
      "--bright-dropbox-copy": "#123329",
      "--bright-dropbox-meta": "#004036",
      "--bright-dropbox-display-font": "var(--font-zine-serif)",
      "--bright-dropbox-body-font": "var(--font-zine-mono)",
      "--bright-dropbox-label-font": "var(--font-zine-grotesque)",
      "--bright-dropbox-heading-letter-spacing": "-0.04em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.18em",
    },
  },
  {
    name: "pool hall",
    values: {
      "--background": "#00d1ff",
      "--foreground": "#07151c",
      "--paper": "#d8fff7",
      "--paper-strong": "#f3fff9",
      "--surface": "#ff6b35",
      "--surface-strong": "#c7ff4f",
      "--border": "rgba(7, 21, 28, 0.24)",
      "--rule": "rgba(7, 21, 28, 0.18)",
      "--muted": "#25424a",
      "--link-hover": "#07151c",
      "--accent": "#8b1dff",
      "--accent-soft": "rgba(139, 29, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(0, 60, 78, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(0, 60, 78, 0.13)",
      "--surface-panel-background": "rgba(243, 255, 249, 0.88)",
      "--surface-card-background": "#f3fff9",
      "--header-surface": "rgba(0, 209, 255, 0.82)",
      "--header-border": "rgba(7, 21, 28, 0.18)",
      "--footer-border": "rgba(7, 21, 28, 0.18)",
      "--intro-surface": "#c7ff4f",
      "--intro-heading": "#07151c",
      "--gallery-divider": "rgba(7, 21, 28, 0.14)",
      "--archive-note-surface": "#07151c",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(243, 255, 249, 0.9)",
        muted: "rgba(243, 255, 249, 0.68)",
        spinner: "rgba(243, 255, 249, 0.82)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(243, 255, 249, 0.82)",
      "--theme-toggle-border": "rgba(7, 21, 28, 0.2)",
      "--theme-toggle-foreground": "rgba(7, 21, 28, 0.64)",
      "--theme-toggle-hover-surface": "rgba(139, 29, 255, 0.12)",
      "--theme-toggle-active-surface": "#8b1dff",
      "--theme-toggle-active-foreground": "#f3fff9",
      "--theme-toggle-shadow": "0 18px 44px rgba(139, 29, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-serif)",
      "--zine-body-font": "var(--font-zine-grotesque)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "-0.035em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.14em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#d8fff7",
      "--bright-opendoor-heading": "#07151c",
      "--bright-opendoor-copy": "#25424a",
      "--bright-opendoor-meta": "#426a70",
      "--bright-opendoor-display-font": "var(--font-zine-grotesque)",
      "--bright-opendoor-body-font": "var(--font-zine-grotesque)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.045em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.1em",
      "--bright-draftkings-surface": "#07151c",
      "--bright-draftkings-heading": "#c7ff4f",
      "--bright-draftkings-copy": "rgba(243, 255, 249, 0.86)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-poster)",
      "--bright-draftkings-body-font": "var(--font-zine-mono)",
      "--bright-draftkings-label-font": "var(--font-zine-grotesque)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.16em",
      "--bright-coinbase-surface": "#8b1dff",
      "--bright-coinbase-heading": "#f3fff9",
      "--bright-coinbase-copy": "rgba(243, 255, 249, 0.86)",
      "--bright-coinbase-meta": "#c7ff4f",
      "--bright-coinbase-display-font": "var(--font-zine-serif)",
      "--bright-coinbase-body-font": "var(--font-zine-grotesque)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "-0.05em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#c7ff4f",
      "--bright-dropbox-heading": "#07151c",
      "--bright-dropbox-copy": "#253317",
      "--bright-dropbox-meta": "#3f5b1a",
      "--bright-dropbox-display-font": "var(--font-zine-poster)",
      "--bright-dropbox-body-font": "var(--font-zine-grotesque)",
      "--bright-dropbox-label-font": "var(--font-zine-mono)",
      "--bright-dropbox-heading-letter-spacing": "0",
      "--bright-dropbox-heading-text-transform": "uppercase",
      "--bright-dropbox-label-letter-spacing": "0.08em",
    },
  },
  {
    name: "poster wall",
    values: {
      "--background": "#ff5c8a",
      "--foreground": "#210713",
      "--paper": "#fff0f5",
      "--paper-strong": "#fff9fb",
      "--surface": "#6cff00",
      "--surface-strong": "#ffd400",
      "--border": "rgba(33, 7, 19, 0.24)",
      "--rule": "rgba(33, 7, 19, 0.18)",
      "--muted": "#5d2637",
      "--link-hover": "#210713",
      "--accent": "#0057ff",
      "--accent-soft": "rgba(0, 87, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(75, 0, 32, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(75, 0, 32, 0.13)",
      "--surface-panel-background": "rgba(255, 249, 251, 0.88)",
      "--surface-card-background": "#fff9fb",
      "--header-surface": "rgba(255, 92, 138, 0.82)",
      "--header-border": "rgba(33, 7, 19, 0.18)",
      "--footer-border": "rgba(33, 7, 19, 0.18)",
      "--intro-surface": "#ffd400",
      "--intro-heading": "#210713",
      "--gallery-divider": "rgba(33, 7, 19, 0.14)",
      "--archive-note-surface": "#210713",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.22)",
        foreground: "rgba(255, 249, 251, 0.9)",
        muted: "rgba(255, 249, 251, 0.68)",
        spinner: "rgba(255, 249, 251, 0.82)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 249, 251, 0.82)",
      "--theme-toggle-border": "rgba(33, 7, 19, 0.2)",
      "--theme-toggle-foreground": "rgba(33, 7, 19, 0.64)",
      "--theme-toggle-hover-surface": "rgba(0, 87, 255, 0.12)",
      "--theme-toggle-active-surface": "#0057ff",
      "--theme-toggle-active-foreground": "#fff9fb",
      "--theme-toggle-shadow": "0 18px 44px rgba(0, 87, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-grotesque)",
      "--zine-body-font": "var(--font-zine-grotesque)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "-0.04em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.16em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fff9fb",
      "--bright-opendoor-heading": "#210713",
      "--bright-opendoor-copy": "#5d2637",
      "--bright-opendoor-meta": "#83384e",
      "--bright-opendoor-display-font": "var(--font-zine-serif)",
      "--bright-opendoor-body-font": "var(--font-zine-grotesque)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.055em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.18em",
      "--bright-draftkings-surface": "#210713",
      "--bright-draftkings-heading": "#6cff00",
      "--bright-draftkings-copy": "rgba(255, 249, 251, 0.86)",
      "--bright-draftkings-meta": "#ffd400",
      "--bright-draftkings-display-font": "var(--font-zine-poster)",
      "--bright-draftkings-body-font": "var(--font-zine-grotesque)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#0057ff",
      "--bright-coinbase-heading": "#fff9fb",
      "--bright-coinbase-copy": "rgba(255, 249, 251, 0.86)",
      "--bright-coinbase-meta": "#6cff00",
      "--bright-coinbase-display-font": "var(--font-zine-grotesque)",
      "--bright-coinbase-body-font": "var(--font-zine-mono)",
      "--bright-coinbase-label-font": "var(--font-zine-grotesque)",
      "--bright-coinbase-heading-letter-spacing": "-0.035em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.2em",
      "--bright-dropbox-surface": "#6cff00",
      "--bright-dropbox-heading": "#210713",
      "--bright-dropbox-copy": "#283d13",
      "--bright-dropbox-meta": "#3d5f12",
      "--bright-dropbox-display-font": "var(--font-zine-serif)",
      "--bright-dropbox-body-font": "var(--font-zine-grotesque)",
      "--bright-dropbox-label-font": "var(--font-zine-mono)",
      "--bright-dropbox-heading-letter-spacing": "-0.06em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.12em",
    },
  },
  {
    name: "electric tabloid",
    values: {
      "--background": "#1affd5",
      "--foreground": "#101118",
      "--paper": "#fff7d1",
      "--paper-strong": "#fffdf4",
      "--surface": "#ff4fd8",
      "--surface-strong": "#fff04a",
      "--border": "rgba(16, 17, 24, 0.24)",
      "--rule": "rgba(16, 17, 24, 0.18)",
      "--muted": "#3f4952",
      "--link-hover": "#101118",
      "--accent": "#5d2cff",
      "--accent-soft": "rgba(93, 44, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(13, 79, 72, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(13, 79, 72, 0.12)",
      "--surface-panel-background": "rgba(255, 253, 244, 0.88)",
      "--surface-card-background": "#fffdf4",
      "--header-surface": "rgba(26, 255, 213, 0.82)",
      "--header-border": "rgba(16, 17, 24, 0.18)",
      "--footer-border": "rgba(16, 17, 24, 0.18)",
      "--intro-surface": "#fff04a",
      "--intro-heading": "#101118",
      "--gallery-divider": "rgba(16, 17, 24, 0.14)",
      "--archive-note-surface": "#101118",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.22)",
        foreground: "rgba(255, 253, 244, 0.9)",
        muted: "rgba(255, 253, 244, 0.68)",
        spinner: "rgba(255, 253, 244, 0.82)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 253, 244, 0.84)",
      "--theme-toggle-border": "rgba(16, 17, 24, 0.2)",
      "--theme-toggle-foreground": "rgba(16, 17, 24, 0.66)",
      "--theme-toggle-hover-surface": "rgba(93, 44, 255, 0.12)",
      "--theme-toggle-active-surface": "#5d2cff",
      "--theme-toggle-active-foreground": "#fffdf4",
      "--theme-toggle-shadow": "0 18px 44px rgba(93, 44, 255, 0.22)",
      "--zine-display-font": "var(--font-zine-modern)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-condensed)",
      "--zine-heading-letter-spacing": "0",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.1em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffdf4",
      "--bright-opendoor-heading": "#101118",
      "--bright-opendoor-copy": "#3f2d1f",
      "--bright-opendoor-meta": "#6c4f24",
      "--bright-opendoor-display-font": "var(--font-zine-classic)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.035em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.14em",
      "--bright-draftkings-surface": "#101118",
      "--bright-draftkings-heading": "#1affd5",
      "--bright-draftkings-copy": "rgba(255, 253, 244, 0.88)",
      "--bright-draftkings-meta": "#fff04a",
      "--bright-draftkings-display-font": "var(--font-zine-modern)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#5d2cff",
      "--bright-coinbase-heading": "#fffdf4",
      "--bright-coinbase-copy": "rgba(255, 253, 244, 0.88)",
      "--bright-coinbase-meta": "#1affd5",
      "--bright-coinbase-display-font": "var(--font-zine-condensed)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.16em",
      "--bright-dropbox-surface": "#ff4fd8",
      "--bright-dropbox-heading": "#101118",
      "--bright-dropbox-copy": "#341128",
      "--bright-dropbox-meta": "#5d143f",
      "--bright-dropbox-display-font": "var(--font-zine-classic)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-condensed)",
      "--bright-dropbox-heading-letter-spacing": "-0.045em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.18em",
    },
  },
  {
    name: "museum flyer",
    values: {
      "--background": "#ffe2ef",
      "--foreground": "#160d18",
      "--paper": "#fff9f0",
      "--paper-strong": "#fffdf8",
      "--surface": "#8cffd2",
      "--surface-strong": "#f8ff7a",
      "--border": "rgba(22, 13, 24, 0.23)",
      "--rule": "rgba(22, 13, 24, 0.17)",
      "--muted": "#4b394e",
      "--link-hover": "#160d18",
      "--accent": "#f24b00",
      "--accent-soft": "rgba(242, 75, 0, 0.18)",
      "--shadow": "0 35px 90px rgba(70, 25, 52, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(70, 25, 52, 0.12)",
      "--surface-panel-background": "rgba(255, 253, 248, 0.9)",
      "--surface-card-background": "#fffdf8",
      "--header-surface": "rgba(255, 226, 239, 0.84)",
      "--header-border": "rgba(22, 13, 24, 0.18)",
      "--footer-border": "rgba(22, 13, 24, 0.18)",
      "--intro-surface": "#8cffd2",
      "--intro-heading": "#160d18",
      "--gallery-divider": "rgba(22, 13, 24, 0.14)",
      "--archive-note-surface": "#160d18",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(255, 253, 248, 0.9)",
        muted: "rgba(255, 253, 248, 0.68)",
        spinner: "rgba(255, 253, 248, 0.82)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 253, 248, 0.84)",
      "--theme-toggle-border": "rgba(22, 13, 24, 0.2)",
      "--theme-toggle-foreground": "rgba(22, 13, 24, 0.66)",
      "--theme-toggle-hover-surface": "rgba(242, 75, 0, 0.12)",
      "--theme-toggle-active-surface": "#f24b00",
      "--theme-toggle-active-foreground": "#fffdf8",
      "--theme-toggle-shadow": "0 18px 44px rgba(242, 75, 0, 0.18)",
      "--zine-display-font": "var(--font-zine-classic)",
      "--zine-body-font": "var(--font-zine-grotesque)",
      "--zine-label-font": "var(--font-zine-condensed)",
      "--zine-heading-letter-spacing": "-0.04em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.16em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffdf8",
      "--bright-opendoor-heading": "#160d18",
      "--bright-opendoor-copy": "#4b394e",
      "--bright-opendoor-meta": "#785a6d",
      "--bright-opendoor-display-font": "var(--font-zine-classic)",
      "--bright-opendoor-body-font": "var(--font-zine-grotesque)",
      "--bright-opendoor-label-font": "var(--font-zine-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.05em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#160d18",
      "--bright-draftkings-heading": "#f8ff7a",
      "--bright-draftkings-copy": "rgba(255, 253, 248, 0.88)",
      "--bright-draftkings-meta": "#8cffd2",
      "--bright-draftkings-display-font": "var(--font-zine-condensed)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#f24b00",
      "--bright-coinbase-heading": "#fffdf8",
      "--bright-coinbase-copy": "rgba(255, 253, 248, 0.88)",
      "--bright-coinbase-meta": "#f8ff7a",
      "--bright-coinbase-display-font": "var(--font-zine-modern)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#8cffd2",
      "--bright-dropbox-heading": "#160d18",
      "--bright-dropbox-copy": "#183d33",
      "--bright-dropbox-meta": "#275d4e",
      ...dropboxTypographyPresets.serifCondensed,
    },
  },
  {
    name: "signal garden",
    values: {
      "--background": "#b7ff00",
      "--foreground": "#0b170d",
      "--paper": "#f7ffe0",
      "--paper-strong": "#fdfff2",
      "--surface": "#00c2ff",
      "--surface-strong": "#ff7a00",
      "--border": "rgba(11, 23, 13, 0.24)",
      "--rule": "rgba(11, 23, 13, 0.18)",
      "--muted": "#31442b",
      "--link-hover": "#0b170d",
      "--accent": "#d400ff",
      "--accent-soft": "rgba(212, 0, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(44, 72, 0, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(44, 72, 0, 0.12)",
      "--surface-panel-background": "rgba(253, 255, 242, 0.88)",
      "--surface-card-background": "#fdfff2",
      "--header-surface": "rgba(183, 255, 0, 0.82)",
      "--header-border": "rgba(11, 23, 13, 0.18)",
      "--footer-border": "rgba(11, 23, 13, 0.18)",
      "--intro-surface": "#00c2ff",
      "--intro-heading": "#0b170d",
      "--gallery-divider": "rgba(11, 23, 13, 0.14)",
      "--archive-note-surface": "#0b170d",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(253, 255, 242, 0.9)",
        muted: "rgba(253, 255, 242, 0.68)",
        spinner: "rgba(253, 255, 242, 0.82)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(253, 255, 242, 0.84)",
      "--theme-toggle-border": "rgba(11, 23, 13, 0.2)",
      "--theme-toggle-foreground": "rgba(11, 23, 13, 0.66)",
      "--theme-toggle-hover-surface": "rgba(212, 0, 255, 0.12)",
      "--theme-toggle-active-surface": "#d400ff",
      "--theme-toggle-active-foreground": "#fdfff2",
      "--theme-toggle-shadow": "0 18px 44px rgba(212, 0, 255, 0.18)",
      "--zine-display-font": "var(--font-zine-condensed)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "0",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.14em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fdfff2",
      "--bright-opendoor-heading": "#0b170d",
      "--bright-opendoor-copy": "#31442b",
      "--bright-opendoor-meta": "#4f6b30",
      "--bright-opendoor-display-font": "var(--font-zine-serif)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.045em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#0b170d",
      "--bright-draftkings-heading": "#b7ff00",
      "--bright-draftkings-copy": "rgba(253, 255, 242, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-poster)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-condensed)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.08em",
      "--bright-coinbase-surface": "#00c2ff",
      "--bright-coinbase-heading": "#0b170d",
      "--bright-coinbase-copy": "#102f3b",
      "--bright-coinbase-meta": "#164f62",
      "--bright-coinbase-display-font": "var(--font-zine-modern)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#ff7a00",
      "--bright-dropbox-heading": "#0b170d",
      "--bright-dropbox-copy": "#3f1d00",
      "--bright-dropbox-meta": "#633000",
      "--bright-dropbox-display-font": "var(--font-zine-classic)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-condensed)",
      "--bright-dropbox-heading-letter-spacing": "-0.05em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.16em",
    },
  },
  {
    name: "blueprint bloom",
    values: {
      "--background": "#243bff",
      "--foreground": "#f9fbff",
      "--paper": "#edf3ff",
      "--paper-strong": "#ffffff",
      "--surface": "#ffef5a",
      "--surface-strong": "#ff8cc6",
      "--border": "rgba(249, 251, 255, 0.28)",
      "--rule": "rgba(249, 251, 255, 0.2)",
      "--muted": "rgba(249, 251, 255, 0.72)",
      "--link-hover": "#ffffff",
      "--accent": "#6dff94",
      "--accent-soft": "rgba(109, 255, 148, 0.2)",
      "--shadow": "0 35px 90px rgba(0, 14, 115, 0.24)",
      "--shadow-soft": "0 16px 46px rgba(0, 14, 115, 0.16)",
      "--surface-panel-background": "rgba(255, 255, 255, 0.9)",
      "--surface-card-background": "#ffffff",
      "--header-surface": "rgba(36, 59, 255, 0.84)",
      "--header-border": "rgba(249, 251, 255, 0.2)",
      "--footer-border": "rgba(249, 251, 255, 0.18)",
      "--intro-surface": "#243bff",
      "--intro-heading": "#f9fbff",
      "--gallery-divider": "rgba(249, 251, 255, 0.14)",
      "--archive-note-surface": "#07124f",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.22)",
        foreground: "rgba(249, 251, 255, 0.9)",
        muted: "rgba(249, 251, 255, 0.68)",
        spinner: "rgba(255, 255, 255, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 255, 255, 0.84)",
      "--theme-toggle-border": "rgba(249, 251, 255, 0.28)",
      "--theme-toggle-foreground": "rgba(7, 18, 79, 0.66)",
      "--theme-toggle-hover-surface": "rgba(109, 255, 148, 0.14)",
      "--theme-toggle-active-surface": "#6dff94",
      "--theme-toggle-active-foreground": "#07124f",
      "--theme-toggle-shadow": "0 18px 44px rgba(109, 255, 148, 0.18)",
      "--zine-display-font": "var(--font-zine-modern)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "0",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.12em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#ffffff",
      "--bright-opendoor-heading": "#07124f",
      "--bright-opendoor-copy": "#26305f",
      "--bright-opendoor-meta": "#48528b",
      "--bright-opendoor-display-font": "var(--font-zine-classic)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.045em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#07124f",
      "--bright-draftkings-heading": "#6dff94",
      "--bright-draftkings-copy": "rgba(249, 251, 255, 0.88)",
      "--bright-draftkings-meta": "#ffef5a",
      "--bright-draftkings-display-font": "var(--font-zine-modern)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-condensed)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#ffef5a",
      "--bright-coinbase-heading": "#07124f",
      "--bright-coinbase-copy": "#293057",
      "--bright-coinbase-meta": "#4b5120",
      "--bright-coinbase-display-font": "var(--font-zine-condensed)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#ff8cc6",
      "--bright-dropbox-heading": "#07124f",
      "--bright-dropbox-copy": "#4b1734",
      "--bright-dropbox-meta": "#73264f",
      ...dropboxTypographyPresets.serifCondensed,
    },
  },
  {
    name: "risograph heat",
    values: {
      "--background": "#ff8a00",
      "--foreground": "#1b0f05",
      "--paper": "#fff3df",
      "--paper-strong": "#fffaf1",
      "--surface": "#00e5ff",
      "--surface-strong": "#ff3d68",
      "--border": "rgba(27, 15, 5, 0.24)",
      "--rule": "rgba(27, 15, 5, 0.18)",
      "--muted": "#5b3214",
      "--link-hover": "#1b0f05",
      "--accent": "#1936ff",
      "--accent-soft": "rgba(25, 54, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(92, 42, 0, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(92, 42, 0, 0.13)",
      "--surface-panel-background": "rgba(255, 250, 241, 0.9)",
      "--surface-card-background": "#fffaf1",
      "--header-surface": "rgba(255, 138, 0, 0.84)",
      "--header-border": "rgba(27, 15, 5, 0.18)",
      "--footer-border": "rgba(27, 15, 5, 0.18)",
      "--intro-surface": "#ff3d68",
      "--intro-heading": "#1b0f05",
      "--gallery-divider": "rgba(27, 15, 5, 0.14)",
      "--archive-note-surface": "#1b0f05",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.22)",
        foreground: "rgba(255, 250, 241, 0.9)",
        muted: "rgba(255, 250, 241, 0.68)",
        spinner: "rgba(255, 250, 241, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 250, 241, 0.84)",
      "--theme-toggle-border": "rgba(27, 15, 5, 0.2)",
      "--theme-toggle-foreground": "rgba(27, 15, 5, 0.66)",
      "--theme-toggle-hover-surface": "rgba(25, 54, 255, 0.12)",
      "--theme-toggle-active-surface": "#1936ff",
      "--theme-toggle-active-foreground": "#fffaf1",
      "--theme-toggle-shadow": "0 18px 44px rgba(25, 54, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-poster)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-condensed)",
      "--zine-heading-letter-spacing": "0",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.12em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffaf1",
      "--bright-opendoor-heading": "#1b0f05",
      "--bright-opendoor-copy": "#5b3214",
      "--bright-opendoor-meta": "#87511d",
      "--bright-opendoor-display-font": "var(--font-zine-classic)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.05em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#1b0f05",
      "--bright-draftkings-heading": "#00e5ff",
      "--bright-draftkings-copy": "rgba(255, 250, 241, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-condensed)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#1936ff",
      "--bright-coinbase-heading": "#fffaf1",
      "--bright-coinbase-copy": "rgba(255, 250, 241, 0.88)",
      "--bright-coinbase-meta": "#00e5ff",
      "--bright-coinbase-display-font": "var(--font-zine-modern)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-condensed)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.1em",
      "--bright-dropbox-surface": "#00e5ff",
      "--bright-dropbox-heading": "#1b0f05",
      "--bright-dropbox-copy": "#083b40",
      "--bright-dropbox-meta": "#0d5a62",
      "--bright-dropbox-display-font": "var(--font-zine-serif)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-mono)",
      "--bright-dropbox-heading-letter-spacing": "-0.045em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.16em",
    },
  },
  {
    name: "soft circuit",
    values: {
      "--background": "#e8ff57",
      "--foreground": "#10191f",
      "--paper": "#f8ffe5",
      "--paper-strong": "#fdfff3",
      "--surface": "#57a5ff",
      "--surface-strong": "#ff91e1",
      "--border": "rgba(16, 25, 31, 0.24)",
      "--rule": "rgba(16, 25, 31, 0.18)",
      "--muted": "#354b4e",
      "--link-hover": "#10191f",
      "--accent": "#008a5f",
      "--accent-soft": "rgba(0, 138, 95, 0.18)",
      "--shadow": "0 35px 90px rgba(45, 81, 0, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(45, 81, 0, 0.12)",
      "--surface-panel-background": "rgba(253, 255, 243, 0.9)",
      "--surface-card-background": "#fdfff3",
      "--header-surface": "rgba(232, 255, 87, 0.84)",
      "--header-border": "rgba(16, 25, 31, 0.18)",
      "--footer-border": "rgba(16, 25, 31, 0.18)",
      "--intro-surface": "#ff91e1",
      "--intro-heading": "#10191f",
      "--gallery-divider": "rgba(16, 25, 31, 0.14)",
      "--archive-note-surface": "#10191f",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(253, 255, 243, 0.9)",
        muted: "rgba(253, 255, 243, 0.68)",
        spinner: "rgba(253, 255, 243, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(253, 255, 243, 0.84)",
      "--theme-toggle-border": "rgba(16, 25, 31, 0.2)",
      "--theme-toggle-foreground": "rgba(16, 25, 31, 0.66)",
      "--theme-toggle-hover-surface": "rgba(0, 138, 95, 0.12)",
      "--theme-toggle-active-surface": "#008a5f",
      "--theme-toggle-active-foreground": "#fdfff3",
      "--theme-toggle-shadow": "0 18px 44px rgba(0, 138, 95, 0.18)",
      "--zine-display-font": "var(--font-zine-classic)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-condensed)",
      "--zine-heading-letter-spacing": "-0.045em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.16em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fdfff3",
      "--bright-opendoor-heading": "#10191f",
      "--bright-opendoor-copy": "#354b4e",
      "--bright-opendoor-meta": "#55736d",
      "--bright-opendoor-display-font": "var(--font-zine-serif)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.045em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.16em",
      "--bright-draftkings-surface": "#10191f",
      "--bright-draftkings-heading": "#e8ff57",
      "--bright-draftkings-copy": "rgba(253, 255, 243, 0.88)",
      "--bright-draftkings-meta": "#57a5ff",
      "--bright-draftkings-display-font": "var(--font-zine-modern)",
      "--bright-draftkings-body-font": "var(--font-zine-readable)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#57a5ff",
      "--bright-coinbase-heading": "#10191f",
      "--bright-coinbase-copy": "#132f4f",
      "--bright-coinbase-meta": "#174c7e",
      "--bright-coinbase-display-font": "var(--font-zine-condensed)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-mono)",
      "--bright-coinbase-heading-letter-spacing": "0",
      "--bright-coinbase-heading-text-transform": "uppercase",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#ff91e1",
      "--bright-dropbox-heading": "#10191f",
      "--bright-dropbox-copy": "#4d193c",
      "--bright-dropbox-meta": "#742a5b",
      "--bright-dropbox-display-font": "var(--font-zine-classic)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-condensed)",
      "--bright-dropbox-heading-letter-spacing": "-0.045em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.16em",
    },
  },
  {
    name: "gallery voltage",
    values: {
      "--background": "#ff4fd8",
      "--foreground": "#120919",
      "--paper": "#fff0fb",
      "--paper-strong": "#fff8fd",
      "--surface": "#39ff88",
      "--surface-strong": "#fff04f",
      "--border": "rgba(18, 9, 25, 0.24)",
      "--rule": "rgba(18, 9, 25, 0.18)",
      "--muted": "#4b2548",
      "--link-hover": "#120919",
      "--accent": "#063cff",
      "--accent-soft": "rgba(6, 60, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(94, 0, 68, 0.22)",
      "--shadow-soft": "0 16px 46px rgba(94, 0, 68, 0.14)",
      "--surface-panel-background": "rgba(255, 248, 253, 0.9)",
      "--surface-card-background": "#fff8fd",
      "--header-surface": "rgba(255, 79, 216, 0.84)",
      "--header-border": "rgba(18, 9, 25, 0.18)",
      "--footer-border": "rgba(18, 9, 25, 0.18)",
      "--intro-surface": "#39ff88",
      "--intro-heading": "#120919",
      "--gallery-divider": "rgba(18, 9, 25, 0.14)",
      "--archive-note-surface": "#120919",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(255, 248, 253, 0.9)",
        muted: "rgba(255, 248, 253, 0.68)",
        spinner: "rgba(255, 248, 253, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 248, 253, 0.84)",
      "--theme-toggle-border": "rgba(18, 9, 25, 0.2)",
      "--theme-toggle-foreground": "rgba(18, 9, 25, 0.66)",
      "--theme-toggle-hover-surface": "rgba(6, 60, 255, 0.12)",
      "--theme-toggle-active-surface": "#063cff",
      "--theme-toggle-active-foreground": "#fff8fd",
      "--theme-toggle-shadow": "0 18px 44px rgba(6, 60, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-gallery)",
      "--zine-body-font": "var(--font-zine-product-condensed)",
      "--zine-label-font": "var(--font-zine-compressed)",
      "--zine-heading-letter-spacing": "-0.055em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.08em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fff8fd",
      "--bright-opendoor-heading": "#120919",
      "--bright-opendoor-copy": "#4b2548",
      "--bright-opendoor-meta": "#6f3b67",
      "--bright-opendoor-display-font": "var(--font-zine-literary)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-product-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.04em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.12em",
      "--bright-draftkings-surface": "#120919",
      "--bright-draftkings-heading": "#39ff88",
      "--bright-draftkings-copy": "rgba(255, 248, 253, 0.88)",
      "--bright-draftkings-meta": "#fff04f",
      "--bright-draftkings-display-font": "var(--font-zine-compressed)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0.02em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#063cff",
      "--bright-coinbase-heading": "#fff8fd",
      "--bright-coinbase-copy": "rgba(255, 248, 253, 0.88)",
      "--bright-coinbase-meta": "#39ff88",
      "--bright-coinbase-display-font": "var(--font-zine-gallery)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-product-condensed)",
      "--bright-coinbase-heading-letter-spacing": "-0.045em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.14em",
      "--bright-dropbox-surface": "#fff04f",
      "--bright-dropbox-heading": "#120919",
      "--bright-dropbox-copy": "#473900",
      "--bright-dropbox-meta": "#6f5a00",
      ...dropboxTypographyPresets.elegantCompressed,
    },
  },
  {
    name: "newspaper acid",
    values: {
      "--background": "#f2efe4",
      "--foreground": "#17130e",
      "--paper": "#fffaf0",
      "--paper-strong": "#fffdf7",
      "--surface": "#ff5a1f",
      "--surface-strong": "#c8ff00",
      "--border": "rgba(23, 19, 14, 0.24)",
      "--rule": "rgba(23, 19, 14, 0.18)",
      "--muted": "#534837",
      "--link-hover": "#17130e",
      "--accent": "#0057ff",
      "--accent-soft": "rgba(0, 87, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(73, 52, 20, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(73, 52, 20, 0.12)",
      "--surface-panel-background": "rgba(255, 253, 247, 0.9)",
      "--surface-card-background": "#fffdf7",
      "--header-surface": "rgba(242, 239, 228, 0.86)",
      "--header-border": "rgba(23, 19, 14, 0.18)",
      "--footer-border": "rgba(23, 19, 14, 0.18)",
      "--intro-surface": "#c8ff00",
      "--intro-heading": "#17130e",
      "--gallery-divider": "rgba(23, 19, 14, 0.14)",
      "--archive-note-surface": "#17130e",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(255, 253, 247, 0.9)",
        muted: "rgba(255, 253, 247, 0.68)",
        spinner: "rgba(255, 253, 247, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 253, 247, 0.84)",
      "--theme-toggle-border": "rgba(23, 19, 14, 0.2)",
      "--theme-toggle-foreground": "rgba(23, 19, 14, 0.66)",
      "--theme-toggle-hover-surface": "rgba(0, 87, 255, 0.12)",
      "--theme-toggle-active-surface": "#0057ff",
      "--theme-toggle-active-foreground": "#fffdf7",
      "--theme-toggle-shadow": "0 18px 44px rgba(0, 87, 255, 0.18)",
      "--zine-display-font": "var(--font-zine-elegant)",
      "--zine-body-font": "var(--font-zine-product-condensed)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "-0.035em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.14em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffdf7",
      "--bright-opendoor-heading": "#17130e",
      "--bright-opendoor-copy": "#534837",
      "--bright-opendoor-meta": "#71654f",
      "--bright-opendoor-display-font": "var(--font-zine-elegant)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-mono)",
      "--bright-opendoor-heading-letter-spacing": "-0.04em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.14em",
      "--bright-draftkings-surface": "#17130e",
      "--bright-draftkings-heading": "#c8ff00",
      "--bright-draftkings-copy": "rgba(255, 253, 247, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-compressed)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0.02em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#0057ff",
      "--bright-coinbase-heading": "#fffdf7",
      "--bright-coinbase-copy": "rgba(255, 253, 247, 0.88)",
      "--bright-coinbase-meta": "#c8ff00",
      "--bright-coinbase-display-font": "var(--font-zine-gallery)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-product-condensed)",
      "--bright-coinbase-heading-letter-spacing": "-0.045em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff5a1f",
      "--bright-dropbox-heading": "#17130e",
      "--bright-dropbox-copy": "#4b1a05",
      "--bright-dropbox-meta": "#6c280a",
      ...dropboxTypographyPresets.literaryCompressed,
    },
  },
  {
    name: "metro bloom",
    values: {
      "--background": "#00b982",
      "--foreground": "#071b16",
      "--paper": "#eafff6",
      "--paper-strong": "#f6fffb",
      "--surface": "#ffcf00",
      "--surface-strong": "#ff7ab6",
      "--border": "rgba(7, 27, 22, 0.24)",
      "--rule": "rgba(7, 27, 22, 0.18)",
      "--muted": "#244a40",
      "--link-hover": "#071b16",
      "--accent": "#4a2cff",
      "--accent-soft": "rgba(74, 44, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(0, 63, 47, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(0, 63, 47, 0.12)",
      "--surface-panel-background": "rgba(246, 255, 251, 0.9)",
      "--surface-card-background": "#f6fffb",
      "--header-surface": "rgba(0, 185, 130, 0.84)",
      "--header-border": "rgba(7, 27, 22, 0.18)",
      "--footer-border": "rgba(7, 27, 22, 0.18)",
      "--intro-surface": "#ffcf00",
      "--intro-heading": "#071b16",
      "--gallery-divider": "rgba(7, 27, 22, 0.14)",
      "--archive-note-surface": "#071b16",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(246, 255, 251, 0.9)",
        muted: "rgba(246, 255, 251, 0.68)",
        spinner: "rgba(246, 255, 251, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(246, 255, 251, 0.84)",
      "--theme-toggle-border": "rgba(7, 27, 22, 0.2)",
      "--theme-toggle-foreground": "rgba(7, 27, 22, 0.66)",
      "--theme-toggle-hover-surface": "rgba(74, 44, 255, 0.12)",
      "--theme-toggle-active-surface": "#4a2cff",
      "--theme-toggle-active-foreground": "#f6fffb",
      "--theme-toggle-shadow": "0 18px 44px rgba(74, 44, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-literary)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-product-condensed)",
      "--zine-heading-letter-spacing": "-0.05em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.14em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#eafff6",
      "--bright-opendoor-heading": "#071b16",
      "--bright-opendoor-copy": "#244a40",
      "--bright-opendoor-meta": "#386d60",
      "--bright-opendoor-display-font": "var(--font-zine-literary)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-product-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.05em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.14em",
      "--bright-draftkings-surface": "#071b16",
      "--bright-draftkings-heading": "#ffcf00",
      "--bright-draftkings-copy": "rgba(246, 255, 251, 0.88)",
      "--bright-draftkings-meta": "#ff7ab6",
      "--bright-draftkings-display-font": "var(--font-zine-compressed)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0.02em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#4a2cff",
      "--bright-coinbase-heading": "#f6fffb",
      "--bright-coinbase-copy": "rgba(246, 255, 251, 0.88)",
      "--bright-coinbase-meta": "#ffcf00",
      "--bright-coinbase-display-font": "var(--font-zine-gallery)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-product-condensed)",
      "--bright-coinbase-heading-letter-spacing": "-0.045em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff7ab6",
      "--bright-dropbox-heading": "#071b16",
      "--bright-dropbox-copy": "#4f1330",
      "--bright-dropbox-meta": "#7b214d",
      ...dropboxTypographyPresets.elegantCompressed,
    },
  },
  {
    name: "chrome candy",
    values: {
      "--background": "#d7e3ff",
      "--foreground": "#101727",
      "--paper": "#f3f6ff",
      "--paper-strong": "#fbfcff",
      "--surface": "#ff3b30",
      "--surface-strong": "#20e3ff",
      "--border": "rgba(16, 23, 39, 0.24)",
      "--rule": "rgba(16, 23, 39, 0.18)",
      "--muted": "#39455f",
      "--link-hover": "#101727",
      "--accent": "#7c3cff",
      "--accent-soft": "rgba(124, 60, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(40, 57, 106, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(40, 57, 106, 0.12)",
      "--surface-panel-background": "rgba(251, 252, 255, 0.9)",
      "--surface-card-background": "#fbfcff",
      "--header-surface": "rgba(215, 227, 255, 0.86)",
      "--header-border": "rgba(16, 23, 39, 0.18)",
      "--footer-border": "rgba(16, 23, 39, 0.18)",
      "--intro-surface": "#20e3ff",
      "--intro-heading": "#101727",
      "--gallery-divider": "rgba(16, 23, 39, 0.14)",
      "--archive-note-surface": "#101727",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(251, 252, 255, 0.9)",
        muted: "rgba(251, 252, 255, 0.68)",
        spinner: "rgba(251, 252, 255, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(251, 252, 255, 0.84)",
      "--theme-toggle-border": "rgba(16, 23, 39, 0.2)",
      "--theme-toggle-foreground": "rgba(16, 23, 39, 0.66)",
      "--theme-toggle-hover-surface": "rgba(124, 60, 255, 0.12)",
      "--theme-toggle-active-surface": "#7c3cff",
      "--theme-toggle-active-foreground": "#fbfcff",
      "--theme-toggle-shadow": "0 18px 44px rgba(124, 60, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-gallery)",
      "--zine-body-font": "var(--font-zine-product-condensed)",
      "--zine-label-font": "var(--font-zine-mono)",
      "--zine-heading-letter-spacing": "-0.055em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.14em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fbfcff",
      "--bright-opendoor-heading": "#101727",
      "--bright-opendoor-copy": "#39455f",
      "--bright-opendoor-meta": "#5a6680",
      "--bright-opendoor-display-font": "var(--font-zine-elegant)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-product-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.035em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.14em",
      "--bright-draftkings-surface": "#101727",
      "--bright-draftkings-heading": "#20e3ff",
      "--bright-draftkings-copy": "rgba(251, 252, 255, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-compressed)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0.02em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#7c3cff",
      "--bright-coinbase-heading": "#fbfcff",
      "--bright-coinbase-copy": "rgba(251, 252, 255, 0.88)",
      "--bright-coinbase-meta": "#20e3ff",
      "--bright-coinbase-display-font": "var(--font-zine-gallery)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-product-condensed)",
      "--bright-coinbase-heading-letter-spacing": "-0.045em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff3b30",
      "--bright-dropbox-heading": "#101727",
      "--bright-dropbox-copy": "#4f120f",
      "--bright-dropbox-meta": "#7a1e18",
      ...dropboxTypographyPresets.literaryCompressed,
    },
  },
  {
    name: "studio fruit",
    values: {
      "--background": "#ffb000",
      "--foreground": "#1f1400",
      "--paper": "#fff5d8",
      "--paper-strong": "#fffaf0",
      "--surface": "#1ae5be",
      "--surface-strong": "#ff6a8a",
      "--border": "rgba(31, 20, 0, 0.24)",
      "--rule": "rgba(31, 20, 0, 0.18)",
      "--muted": "#5d430f",
      "--link-hover": "#1f1400",
      "--accent": "#2447ff",
      "--accent-soft": "rgba(36, 71, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(90, 54, 0, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(90, 54, 0, 0.12)",
      "--surface-panel-background": "rgba(255, 250, 240, 0.9)",
      "--surface-card-background": "#fffaf0",
      "--header-surface": "rgba(255, 176, 0, 0.84)",
      "--header-border": "rgba(31, 20, 0, 0.18)",
      "--footer-border": "rgba(31, 20, 0, 0.18)",
      "--intro-surface": "#1ae5be",
      "--intro-heading": "#1f1400",
      "--gallery-divider": "rgba(31, 20, 0, 0.14)",
      "--archive-note-surface": "#1f1400",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(255, 250, 240, 0.9)",
        muted: "rgba(255, 250, 240, 0.68)",
        spinner: "rgba(255, 250, 240, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 250, 240, 0.84)",
      "--theme-toggle-border": "rgba(31, 20, 0, 0.2)",
      "--theme-toggle-foreground": "rgba(31, 20, 0, 0.66)",
      "--theme-toggle-hover-surface": "rgba(36, 71, 255, 0.12)",
      "--theme-toggle-active-surface": "#2447ff",
      "--theme-toggle-active-foreground": "#fffaf0",
      "--theme-toggle-shadow": "0 18px 44px rgba(36, 71, 255, 0.2)",
      "--zine-display-font": "var(--font-zine-compressed)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-product-condensed)",
      "--zine-heading-letter-spacing": "0.01em",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.12em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#fffaf0",
      "--bright-opendoor-heading": "#1f1400",
      "--bright-opendoor-copy": "#5d430f",
      "--bright-opendoor-meta": "#80611d",
      "--bright-opendoor-display-font": "var(--font-zine-literary)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-product-condensed)",
      "--bright-opendoor-heading-letter-spacing": "-0.05em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.14em",
      "--bright-draftkings-surface": "#1f1400",
      "--bright-draftkings-heading": "#1ae5be",
      "--bright-draftkings-copy": "rgba(255, 250, 240, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-compressed)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-mono)",
      "--bright-draftkings-heading-letter-spacing": "0.02em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.12em",
      "--bright-coinbase-surface": "#2447ff",
      "--bright-coinbase-heading": "#fffaf0",
      "--bright-coinbase-copy": "rgba(255, 250, 240, 0.88)",
      "--bright-coinbase-meta": "#1ae5be",
      "--bright-coinbase-display-font": "var(--font-zine-gallery)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-product-condensed)",
      "--bright-coinbase-heading-letter-spacing": "-0.045em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff6a8a",
      "--bright-dropbox-heading": "#1f1400",
      "--bright-dropbox-copy": "#551321",
      "--bright-dropbox-meta": "#7d2034",
      ...dropboxTypographyPresets.elegantCompressed,
    },
  },
  {
    name: "acid open house",
    values: {
      "--background": "#7bff00",
      "--foreground": "#15091f",
      "--paper": "#f8ffe8",
      "--paper-strong": "#fdfff4",
      "--surface": "#ff2bd6",
      "--surface-strong": "#1511ff",
      "--border": "rgba(21, 9, 31, 0.24)",
      "--rule": "rgba(21, 9, 31, 0.18)",
      "--muted": "#3c2850",
      "--link-hover": "#15091f",
      "--accent": "#ff5a00",
      "--accent-soft": "rgba(255, 90, 0, 0.18)",
      "--shadow": "0 35px 90px rgba(34, 90, 0, 0.22)",
      "--shadow-soft": "0 16px 46px rgba(34, 90, 0, 0.14)",
      "--surface-panel-background": "rgba(253, 255, 244, 0.9)",
      "--surface-card-background": "#fdfff4",
      "--header-surface": "rgba(123, 255, 0, 0.84)",
      "--header-border": "rgba(21, 9, 31, 0.18)",
      "--footer-border": "rgba(21, 9, 31, 0.18)",
      "--intro-surface": "#ff2bd6",
      "--intro-heading": "#15091f",
      "--gallery-divider": "rgba(21, 9, 31, 0.14)",
      "--archive-note-surface": "#15091f",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(253, 255, 244, 0.9)",
        muted: "rgba(253, 255, 244, 0.68)",
        spinner: "rgba(253, 255, 244, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(253, 255, 244, 0.84)",
      "--theme-toggle-border": "rgba(21, 9, 31, 0.2)",
      "--theme-toggle-foreground": "rgba(21, 9, 31, 0.66)",
      "--theme-toggle-hover-surface": "rgba(255, 90, 0, 0.14)",
      "--theme-toggle-active-surface": "#ff5a00",
      "--theme-toggle-active-foreground": "#fdfff4",
      "--theme-toggle-shadow": "0 18px 44px rgba(255, 90, 0, 0.22)",
      "--zine-display-font": "var(--font-zine-brutalist)",
      "--zine-body-font": "var(--font-zine-product-condensed)",
      "--zine-label-font": "var(--font-zine-code)",
      "--zine-heading-letter-spacing": "-0.08em",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.1em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#1511ff",
      "--bright-opendoor-heading": "#7bff00",
      "--bright-opendoor-copy": "rgba(253, 255, 244, 0.9)",
      "--bright-opendoor-meta": "#ff2bd6",
      "--bright-opendoor-display-font": "var(--font-zine-brutalist)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-code)",
      "--bright-opendoor-heading-letter-spacing": "-0.08em",
      "--bright-opendoor-heading-text-transform": "uppercase",
      "--bright-opendoor-label-letter-spacing": "0.1em",
      "--bright-draftkings-surface": "#15091f",
      "--bright-draftkings-heading": "#f7f4ef",
      "--bright-draftkings-copy": "rgba(253, 255, 244, 0.88)",
      "--bright-draftkings-meta": "#7bff00",
      "--bright-draftkings-display-font": "var(--font-zine-arcade)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-code)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#fdfff4",
      "--bright-coinbase-heading": "#15091f",
      "--bright-coinbase-copy": "#3c2850",
      "--bright-coinbase-meta": "#1511ff",
      "--bright-coinbase-display-font": "var(--font-zine-variable)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-code)",
      "--bright-coinbase-heading-letter-spacing": "-0.055em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff2bd6",
      "--bright-dropbox-heading": "#15091f",
      "--bright-dropbox-copy": "#4e123f",
      "--bright-dropbox-meta": "#1511ff",
      ...dropboxTypographyPresets.inkTypewriter,
    },
  },
  {
    name: "xerox carnival",
    values: {
      "--background": "#f7efe3",
      "--foreground": "#100f0d",
      "--paper": "#fff8ed",
      "--paper-strong": "#fffdf7",
      "--surface": "#101010",
      "--surface-strong": "#ffd400",
      "--border": "rgba(16, 15, 13, 0.26)",
      "--rule": "rgba(16, 15, 13, 0.2)",
      "--muted": "#51483b",
      "--link-hover": "#100f0d",
      "--accent": "#e0001b",
      "--accent-soft": "rgba(224, 0, 27, 0.18)",
      "--shadow": "0 35px 90px rgba(55, 42, 23, 0.2)",
      "--shadow-soft": "0 16px 46px rgba(55, 42, 23, 0.13)",
      "--surface-panel-background": "rgba(255, 253, 247, 0.9)",
      "--surface-card-background": "#fffdf7",
      "--header-surface": "rgba(247, 239, 227, 0.86)",
      "--header-border": "rgba(16, 15, 13, 0.18)",
      "--footer-border": "rgba(16, 15, 13, 0.18)",
      "--intro-surface": "#ffd400",
      "--intro-heading": "#100f0d",
      "--gallery-divider": "rgba(16, 15, 13, 0.14)",
      "--archive-note-surface": "#100f0d",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(255, 253, 247, 0.9)",
        muted: "rgba(255, 253, 247, 0.68)",
        spinner: "rgba(255, 253, 247, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(255, 253, 247, 0.84)",
      "--theme-toggle-border": "rgba(16, 15, 13, 0.2)",
      "--theme-toggle-foreground": "rgba(16, 15, 13, 0.66)",
      "--theme-toggle-hover-surface": "rgba(224, 0, 27, 0.12)",
      "--theme-toggle-active-surface": "#e0001b",
      "--theme-toggle-active-foreground": "#fffdf7",
      "--theme-toggle-shadow": "0 18px 44px rgba(224, 0, 27, 0.18)",
      "--zine-display-font": "var(--font-zine-arcade)",
      "--zine-body-font": "var(--font-zine-product-condensed)",
      "--zine-label-font": "var(--font-zine-typewriter)",
      "--zine-heading-letter-spacing": "-0.025em",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.08em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#ffd400",
      "--bright-opendoor-heading": "#100f0d",
      "--bright-opendoor-copy": "#3f3100",
      "--bright-opendoor-meta": "#e0001b",
      "--bright-opendoor-display-font": "var(--font-zine-arcade)",
      "--bright-opendoor-body-font": "var(--font-zine-product-condensed)",
      "--bright-opendoor-label-font": "var(--font-zine-typewriter)",
      "--bright-opendoor-heading-letter-spacing": "-0.025em",
      "--bright-opendoor-heading-text-transform": "uppercase",
      "--bright-opendoor-label-letter-spacing": "0.08em",
      "--bright-draftkings-surface": "#100f0d",
      "--bright-draftkings-heading": "#ffd400",
      "--bright-draftkings-copy": "rgba(255, 253, 247, 0.88)",
      "--bright-draftkings-meta": "#e0001b",
      "--bright-draftkings-display-font": "var(--font-zine-brutalist)",
      "--bright-draftkings-body-font": "var(--font-zine-code)",
      "--bright-draftkings-label-font": "var(--font-zine-typewriter)",
      "--bright-draftkings-heading-letter-spacing": "-0.08em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.08em",
      "--bright-coinbase-surface": "#fffdf7",
      "--bright-coinbase-heading": "#100f0d",
      "--bright-coinbase-copy": "#51483b",
      "--bright-coinbase-meta": "#e0001b",
      "--bright-coinbase-display-font": "var(--font-zine-variable)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-code)",
      "--bright-coinbase-heading-letter-spacing": "-0.055em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#e0001b",
      "--bright-dropbox-heading": "#fffdf7",
      "--bright-dropbox-copy": "rgba(255, 253, 247, 0.88)",
      "--bright-dropbox-meta": "#ffd400",
      ...dropboxTypographyPresets.inkTypewriter,
    },
  },
  {
    name: "sports page bruise",
    values: {
      "--background": "#1a092b",
      "--foreground": "#fff6d8",
      "--paper": "#2a103f",
      "--paper-strong": "#33154b",
      "--surface": "#00ff66",
      "--surface-strong": "#ffea00",
      "--border": "rgba(255, 246, 216, 0.2)",
      "--rule": "rgba(255, 246, 216, 0.16)",
      "--muted": "rgba(255, 246, 216, 0.72)",
      "--link-hover": "#fff6d8",
      "--accent": "#ff3b8b",
      "--accent-soft": "rgba(255, 59, 139, 0.18)",
      "--shadow": "0 35px 90px rgba(0, 0, 0, 0.3)",
      "--shadow-soft": "0 16px 46px rgba(0, 0, 0, 0.2)",
      "--surface-panel-background": "rgba(42, 16, 63, 0.9)",
      "--surface-card-background": "#33154b",
      "--header-surface": "rgba(26, 9, 43, 0.84)",
      "--header-border": "rgba(255, 246, 216, 0.16)",
      "--footer-border": "rgba(255, 246, 216, 0.16)",
      "--intro-surface": "#1a092b",
      "--intro-heading": "#00ff66",
      "--gallery-divider": "rgba(255, 246, 216, 0.14)",
      "--archive-note-surface": "#fff6d8",
      ...archiveFrameTokens({
        border: "rgba(26, 9, 43, 0.18)",
        foreground: "#1a092b",
        muted: "#62416f",
        spinner: "rgba(51, 21, 75, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(51, 21, 75, 0.84)",
      "--theme-toggle-border": "rgba(255, 246, 216, 0.2)",
      "--theme-toggle-foreground": "rgba(255, 246, 216, 0.72)",
      "--theme-toggle-hover-surface": "rgba(0, 255, 102, 0.14)",
      "--theme-toggle-active-surface": "#00ff66",
      "--theme-toggle-active-foreground": "#1a092b",
      "--theme-toggle-shadow": "0 18px 44px rgba(0, 255, 102, 0.18)",
      "--zine-display-font": "var(--font-zine-brutalist)",
      "--zine-body-font": "var(--font-zine-code)",
      "--zine-label-font": "var(--font-zine-compressed)",
      "--zine-heading-letter-spacing": "-0.085em",
      "--zine-heading-text-transform": "uppercase",
      "--zine-body-letter-spacing": "-0.02em",
      "--zine-label-letter-spacing": "0.08em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#ffea00",
      "--bright-opendoor-heading": "#1a092b",
      "--bright-opendoor-copy": "#3b2550",
      "--bright-opendoor-meta": "#ff3b8b",
      "--bright-opendoor-display-font": "var(--font-zine-ink)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-compressed)",
      "--bright-opendoor-heading-letter-spacing": "-0.065em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.08em",
      "--bright-draftkings-surface": "#1a092b",
      "--bright-draftkings-heading": "#00ff66",
      "--bright-draftkings-copy": "rgba(255, 246, 216, 0.88)",
      "--bright-draftkings-meta": "#ffea00",
      "--bright-draftkings-display-font": "var(--font-zine-brutalist)",
      "--bright-draftkings-body-font": "var(--font-zine-code)",
      "--bright-draftkings-label-font": "var(--font-zine-compressed)",
      "--bright-draftkings-heading-letter-spacing": "-0.08em",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.08em",
      "--bright-coinbase-surface": "#33154b",
      "--bright-coinbase-heading": "#fff6d8",
      "--bright-coinbase-copy": "rgba(255, 246, 216, 0.86)",
      "--bright-coinbase-meta": "#00ff66",
      "--bright-coinbase-display-font": "var(--font-zine-variable)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-code)",
      "--bright-coinbase-heading-letter-spacing": "-0.055em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#ff3b8b",
      "--bright-dropbox-heading": "#1a092b",
      "--bright-dropbox-copy": "#4d0f2b",
      "--bright-dropbox-meta": "#ffea00",
      "--bright-dropbox-display-font": "var(--font-zine-arcade)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-typewriter)",
      "--bright-dropbox-heading-letter-spacing": "-0.02em",
      "--bright-dropbox-heading-text-transform": "uppercase",
      "--bright-dropbox-label-letter-spacing": "0.08em",
    },
  },
  {
    name: "soft machine panic",
    values: {
      "--background": "#b9f4ff",
      "--foreground": "#231118",
      "--paper": "#f3fdff",
      "--paper-strong": "#fbfeff",
      "--surface": "#ff8a00",
      "--surface-strong": "#f3ff2f",
      "--border": "rgba(35, 17, 24, 0.24)",
      "--rule": "rgba(35, 17, 24, 0.18)",
      "--muted": "#593243",
      "--link-hover": "#231118",
      "--accent": "#cc00ff",
      "--accent-soft": "rgba(204, 0, 255, 0.18)",
      "--shadow": "0 35px 90px rgba(0, 85, 105, 0.18)",
      "--shadow-soft": "0 16px 46px rgba(0, 85, 105, 0.12)",
      "--surface-panel-background": "rgba(251, 254, 255, 0.9)",
      "--surface-card-background": "#fbfeff",
      "--header-surface": "rgba(185, 244, 255, 0.84)",
      "--header-border": "rgba(35, 17, 24, 0.18)",
      "--footer-border": "rgba(35, 17, 24, 0.18)",
      "--intro-surface": "#f3ff2f",
      "--intro-heading": "#231118",
      "--gallery-divider": "rgba(35, 17, 24, 0.14)",
      "--archive-note-surface": "#231118",
      ...archiveFrameTokens({
        border: "rgba(255, 255, 255, 0.2)",
        foreground: "rgba(251, 254, 255, 0.9)",
        muted: "rgba(251, 254, 255, 0.68)",
        spinner: "rgba(251, 254, 255, 0.84)",
      }),
      "--app-background-gradient": "var(--background)",
      "--site-noise-overlay": "none",
      "--site-noise-opacity": "0",
      "--theme-toggle-surface": "rgba(251, 254, 255, 0.84)",
      "--theme-toggle-border": "rgba(35, 17, 24, 0.2)",
      "--theme-toggle-foreground": "rgba(35, 17, 24, 0.66)",
      "--theme-toggle-hover-surface": "rgba(204, 0, 255, 0.12)",
      "--theme-toggle-active-surface": "#cc00ff",
      "--theme-toggle-active-foreground": "#fbfeff",
      "--theme-toggle-shadow": "0 18px 44px rgba(204, 0, 255, 0.18)",
      "--zine-display-font": "var(--font-zine-variable)",
      "--zine-body-font": "var(--font-zine-readable)",
      "--zine-label-font": "var(--font-zine-typewriter)",
      "--zine-heading-letter-spacing": "-0.065em",
      "--zine-heading-text-transform": "none",
      "--zine-body-letter-spacing": "0",
      "--zine-label-letter-spacing": "0.08em",
      "--zine-label-text-transform": "uppercase",
      "--bright-opendoor-surface": "#ff8a00",
      "--bright-opendoor-heading": "#231118",
      "--bright-opendoor-copy": "#5a2900",
      "--bright-opendoor-meta": "#cc00ff",
      "--bright-opendoor-display-font": "var(--font-zine-typewriter)",
      "--bright-opendoor-body-font": "var(--font-zine-readable)",
      "--bright-opendoor-label-font": "var(--font-zine-code)",
      "--bright-opendoor-heading-letter-spacing": "-0.015em",
      "--bright-opendoor-heading-text-transform": "none",
      "--bright-opendoor-label-letter-spacing": "0.12em",
      "--bright-draftkings-surface": "#231118",
      "--bright-draftkings-heading": "#f3ff2f",
      "--bright-draftkings-copy": "rgba(251, 254, 255, 0.88)",
      "--bright-draftkings-meta": "#a8a29a",
      "--bright-draftkings-display-font": "var(--font-zine-arcade)",
      "--bright-draftkings-body-font": "var(--font-zine-product-condensed)",
      "--bright-draftkings-label-font": "var(--font-zine-code)",
      "--bright-draftkings-heading-letter-spacing": "0",
      "--bright-draftkings-heading-text-transform": "uppercase",
      "--bright-draftkings-label-letter-spacing": "0.1em",
      "--bright-coinbase-surface": "#b9f4ff",
      "--bright-coinbase-heading": "#231118",
      "--bright-coinbase-copy": "#2d4a54",
      "--bright-coinbase-meta": "#cc00ff",
      "--bright-coinbase-display-font": "var(--font-zine-variable)",
      "--bright-coinbase-body-font": "var(--font-zine-readable)",
      "--bright-coinbase-label-font": "var(--font-zine-code)",
      "--bright-coinbase-heading-letter-spacing": "-0.055em",
      "--bright-coinbase-heading-text-transform": "none",
      "--bright-coinbase-label-letter-spacing": "0.12em",
      "--bright-dropbox-surface": "#f3ff2f",
      "--bright-dropbox-heading": "#231118",
      "--bright-dropbox-copy": "#4e5200",
      "--bright-dropbox-meta": "#cc00ff",
      "--bright-dropbox-display-font": "var(--font-zine-ink)",
      "--bright-dropbox-body-font": "var(--font-zine-readable)",
      "--bright-dropbox-label-font": "var(--font-zine-typewriter)",
      "--bright-dropbox-heading-letter-spacing": "-0.055em",
      "--bright-dropbox-heading-text-transform": "none",
      "--bright-dropbox-label-letter-spacing": "0.08em",
    },
  },
];

function getRandomBrightPalette(excludedPaletteNames: readonly string[] = []) {
  const excludedNames = new Set(excludedPaletteNames);
  const availablePalettes = excludedNames.size > 0
    ? brightPalettes.filter((palette) => !excludedNames.has(palette.name))
    : brightPalettes;
  const palettePool = availablePalettes.length > 0
    ? availablePalettes
    : brightPalettes;

  return palettePool[Math.floor(Math.random() * palettePool.length)];
}

function clearBrightPalette(target: HTMLElement) {
  brightThemeVariables.forEach((property) => {
    target.style.removeProperty(property);
  });
}

function getRandomOverscrollBackdrop() {
  return overscrollBackdrops[
    Math.floor(Math.random() * overscrollBackdrops.length)
  ];
}

function getRandomIntroCompanyHoverColors() {
  const colors = [...overscrollBackdrops];

  for (let index = colors.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [colors[index], colors[swapIndex]] = [colors[swapIndex], colors[index]];
  }

  return colors.slice(0, introCompanyHoverVariables.length);
}

function applyIntroCompanyHoverColors(target: HTMLElement) {
  const colors = getRandomIntroCompanyHoverColors();

  introCompanyHoverVariables.forEach((property, index) => {
    target.style.setProperty(property, colors[index]);
  });
}

function ensureIntroCompanyHoverColors(target: HTMLElement) {
  const hasIntroHoverColors = introCompanyHoverVariables.every((property) =>
    Boolean(target.style.getPropertyValue(property)),
  );

  if (!hasIntroHoverColors) {
    applyIntroCompanyHoverColors(target);
  }
}

function applyRandomOverscrollBackdrop(target: HTMLElement) {
  target.style.setProperty(
    "--overscroll-background",
    getRandomOverscrollBackdrop(),
  );
}

function applyBrightPalette(
  target: HTMLElement,
  options: { excludedPaletteNames?: readonly string[] } = {},
) {
  const palette = getRandomBrightPalette(options.excludedPaletteNames);

  clearBrightPalette(target);
  Object.entries(palette.values).forEach(([property, value]) => {
    target.style.setProperty(property, value);
  });
  target.dataset.brightPalette = palette.name;
}

export function applyThemeToDocument(
  theme: ThemeMode,
  options: {
    avoidCurrentBrightPalette?: boolean;
    excludedBrightPaletteName?: string;
  } = {},
) {
  const root = document.documentElement;

  ensureIntroCompanyHoverColors(root);
  root.dataset.theme = theme;
  root.style.colorScheme = theme === "dark" ? "dark" : "light";

  if (theme === "bright") {
    const excludedPaletteNames = [
      options.excludedBrightPaletteName,
      options.avoidCurrentBrightPalette ? root.dataset.brightPalette : undefined,
    ].filter((name): name is string => Boolean(name));

    applyBrightPalette(root, {
      excludedPaletteNames,
    });
    return;
  }

  delete root.dataset.brightPalette;
  clearBrightPalette(root);
  applyRandomOverscrollBackdrop(root);
}

export function dispatchThemeChange(detail: {
  preference: ThemeMode | null;
  resolved: ThemeMode;
}) {
  window.dispatchEvent(new CustomEvent(THEME_CHANGE_EVENT, { detail }));
}

export function getThemeInitScript() {
  return `
    (() => {
      try {
        const root = document.documentElement;
        const overscrollBackdrops = ${JSON.stringify(overscrollBackdrops)};
        const retroCursors = ${JSON.stringify(retroCursors)};
        const retroCursorIndex = Math.floor(Math.random() * retroCursors.length);
        root.style.setProperty("--cursor-retro", retroCursors[retroCursorIndex]);

        const introCompanyHoverProperties = ${JSON.stringify(introCompanyHoverVariables)};
        const introCompanyHoverColors = [...overscrollBackdrops];

        for (let index = introCompanyHoverColors.length - 1; index > 0; index -= 1) {
          const swapIndex = Math.floor(Math.random() * (index + 1));
          const current = introCompanyHoverColors[index];
          introCompanyHoverColors[index] = introCompanyHoverColors[swapIndex];
          introCompanyHoverColors[swapIndex] = current;
        }
        introCompanyHoverProperties.forEach((property, index) => {
          root.style.setProperty(property, introCompanyHoverColors[index]);
        });

        const storageKey = ${JSON.stringify(THEME_STORAGE_KEY)};
        const storedValue = window.localStorage.getItem(storageKey);
        const preference =
          storedValue === "dark" || storedValue === "bright" ? storedValue : null;
        const resolved = preference ?? "dark";

        root.dataset.theme = resolved;
        root.style.colorScheme =
          resolved === "dark" ? "dark" : "light";

        if (resolved === "bright") {
          const palettes = ${JSON.stringify(brightPalettes.map((palette) => palette.values))};
          const names = ${JSON.stringify(brightPalettes.map((palette) => palette.name))};
          const properties = ${JSON.stringify(brightThemeVariables)};
          const index = Math.floor(Math.random() * palettes.length);

          properties.forEach((property) => {
            root.style.removeProperty(property);
          });
          Object.entries(palettes[index]).forEach(([property, value]) => {
            root.style.setProperty(property, value);
          });
          root.dataset.brightPalette = names[index];
        } else {
          const overscrollIndex = Math.floor(Math.random() * overscrollBackdrops.length);
          root.style.setProperty(
            "--overscroll-background",
            overscrollBackdrops[overscrollIndex],
          );
        }
      } catch (error) {
        document.documentElement.dataset.theme = "dark";
        document.documentElement.style.colorScheme = "dark";
      }
    })();
  `;
}
